"""Initial schema

Revision ID: f7f258f1e597
Revises: 
Create Date: 2026-03-30 16:26:31.543188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f258f1e597'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('waba_id', sa.String(), nullable=False),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_id'), 'message_logs', ['id'], unique=False)
    op.create_index(op.f('ix_message_logs_message_id'), 'message_logs', ['message_id'], unique=True)
    op.create_index(op.f('ix_message_logs_user_phone'), 'message_logs', ['user_phone'], unique=False)
    op.create_index(op.f('ix_message_logs_waba_id'), 'message_logs', ['waba_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waba_id', sa.String(), nullable=False),
    sa.Column('phone_number_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_phone_number_id'), 'tenants', ['phone_number_id'], unique=True)
    op.create_index(op.f('ix_tenants_waba_id'), 'tenants', ['waba_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_waba_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_phone_number_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_message_logs_waba_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_user_phone'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_message_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_id'), table_name='message_logs')
    op.drop_table('message_logs')
    # ### end Alembic commands ###
